-- AlterTable
ALTER TABLE "Service" ADD COLUMN     "commission10_5" DOUBLE PRECISION,
ADD COLUMN     "commission21" DOUBLE PRECISION,
ADD COLUMN     "commissionExempt" DOUBLE PRECISION,
ADD COLUMN     "impIVA" DOUBLE PRECISION,
ADD COLUMN     "nonComputable" DOUBLE PRECISION,
ADD COLUMN     "taxableBase10_5" DOUBLE PRECISION,
ADD COLUMN     "taxableBase21" DOUBLE PRECISION,
ADD COLUMN     "totalCommissionWithoutVAT" DOUBLE PRECISION,
ADD COLUMN     "vatOnCommission10_5" DOUBLE PRECISION,
ADD COLUMN     "vatOnCommission21" DOUBLE PRECISION;
